%% Wirakorn Thanabat
%% 6809617415

classDiagram
    %% === Resource === %%
    class Resource {
        +MINIMAL_MODE : boolean$
        +MINIMUM_LANDMINE : int$
        +INITIAL_HEALT_POINT : int$
        +HUMAN_PLAYER_AMOUNT : int$
        +COMPUTER_PLAYER_AMOUNT : int$
        +BLAST_DAMAGE : int $
        +BOARD_SIZE : Dimension$
        +rand : Random$
        +stdin : FastReader$
        +stdout : Printer$
    }
    class OBJECTS {
        <<enumeration>>
        NONE
        LANDMINE
        -description : String
        +isSafe() boolean
        +getChar() char
    }
    class TYPE {
        <<enumeration>>
        HUMAN
        COMPUTER
        OTHER
        -description : String
        +getType() String 
    }
    class Dimension {
        <<record>>
        +row : int
        +col : int
    }
    
    %% --- Exceptions --- %%
    class RuntimeException {
        <<Built-in>>
    }
    class InvalidBoardInitializeException {
        <<exception>>
    }
    InvalidBoardInitializeException --|> RuntimeException : extends

    class InvalidGamePlayException {
        <<exception>>
    }
    InvalidGamePlayException --|> RuntimeException : extends

    Resource --> FastReader : instantiates
    Resource --> Printer : instantiates
    Resource ..> Dimension : nested
    Resource ..> TYPE : nested
    Resource ..> OBJECTS : nested
    Resource ..> InvalidBoardInitializeException : nested
    Resource ..> InvalidGamePlayException : nested

    class FastReader {
        FastReader(InputStream din)
        +nextInt() int 
    }

    class Printer {
        Printer(OutputStream out)
        +println(String txt, boolean flush) void
        +turnOf(String type) void
        +showHealthPointOf(String type, int amount) void
        +flush() void
        +bold(String txt) String
    }

    class Selectable {
        <<interface>>
        +choose() Dimension
    }

    class Player {
        <<abstract>>
        -healthPoint : int
        -alive : boolean
        -playerType : TYPE
        +isAlive() boolean
        +getId()* int
        +reduceHealthPointBy(int damage) void
        +choose(Dimension range)* Dimension
    }
    Player ..> Resource : static import
    Player ..|> Selectable : implements

    class PlayerHuman {
        -id : int
        +choose(Dimension range) Dimension
    }
    PlayerHuman --|> Player : extends

    class PlayerComputer {
        -openedPositions : HashSet<Dimension>$
        +choose(Dimension range) Dimension
    }
    PlayerComputer --|> Player : extends

    class Board {
        -board : List~List~OBJECTS~~
        -playerBoard : char[][]
        -dimension : Dimension
        -amountOfLandmines : int
        -openedLandmines : int
        Board(Dimension dimension, int amountOfLandmines)
        +setupBoard() void
        +choose(Dimension dimension) boolean$
        +isReveal(Dimension dimension) boolean
        +isOutOfLandmines() boolean
        +revealAll() void

    }
    Board ..> Resource : static import

    class Operator {
        -players : ArrayList~Player~ 
        -world : Board
        -boardSize : Dimension
        +setupGame() void
        +run() void
        +endGame() void
        -selectSetting() void
        -playersRound() void
        -processSinglePlayerTurn(Player p) void
    }
    Operator --o Player : manages
    Operator --* Board : owns
    Operator ..> Resource : static import

    class TestGame {
        +main(String[] args)$ void
    }
    TestGame --> Operator : instantiates